### ISSUE TITLE
From_sparse not supported

### ISSUE THREAD

**Issue by franziweindel** [microsoft/rankerEval#2]
Hi, 

I am trying to use your package, in particular the from_sparse function for my input data, however it says that rankEval does not support from_sparse. I have also attached a picture of the error. 

Does the package no longer support this input type? 

Thanks, 

Franzi
![binary](https://user-images.githubusercontent.com/84717912/178120415-0b286451-26de-47f1-8c48-fedf524cebc5.jpg)

**Comment by t-schn** [comment]
@franziweindel: Sorry, that has been updated in v0.2.0 and incorporated into from_matrix. The reason for this is that it wasn't clear what the semantics were (like is it a sparse matrix specifying the positive indices as integers or a binary sparse mask). I'll update the documentation to reflect this.

**Comment by t-schn** [comment]
Updated the documenation.
